#' @export
s5.key <- list(
  subscales = c("N1", "N2", "N3", "N4", "N5", "N6", "E1", 
                "E2", "E3", "E4", "E5", "E6", "O1", "O2", "O3", "O4", "O5", "O6", 
                "A1", "A2", "A3", "A4", "A5", "A6", "C1", "C2", "C3", "C4", "C5", 
                "C6"), 
  domains = c("N", "E", "O", "A", "C"), 
  Mid = 0, 
  lims = c(-3, 3, -3, 3), 
  key = c("N1", "E1", "O1", "A1", "C1", "N6", "E6", 
          "O6", "A6", "C6", "N2", "E2", "O2", "A2", "C2", "A5x", "N5", 
          "E5", "O5", "A5", "C5", "N3", "E3", "O3", "A3", "C3", "N4", "E4", 
          "O4", "A4", "C4", "A5x", "N4", "E4", "O4", "A4", "C4", "N3", 
          "E3", "O3", "A3", "C3", "N5", "E5", "O5", "A5", "C5", "A5x", 
          "N2", "E2", "O2", "A2", "C2", "N6", "E6", "O6", "A6", "C6", "N1", 
          "E1", "O1", "A1", "C1", "A5x"), 
  key2 = c("N", "E", "O", "A", 
           "C", "N", "E", "O", "A", "C", "N", "E", "O", "A", "C", "A5x", 
           "N", "E", "O", "A", "C", "N", "E", "O", "A", "C", "N", "E", "O", 
           "A", "C", "A5x", "N", "E", "O", "A", "C", "N", "E", "O", "A", 
           "C", "N", "E", "O", "A", "C", "A5x", "N", "E", "O", "A", "C", 
           "N", "E", "O", "A", "C", "N", "E", "O", "A", "C", "A5x"), 
  rev = c(1L,  1L, 1L, 1L, 1L, -1L, -1L, -1L, -1L, -1L, 1L, 1L, 1L, 1L, 1L, 
          -1L, -1L, -1L, -1L, -1L, -1L, 1L, 1L, 1L, 1L, 1L, -1L, -1L, -1L, 
          -1L, -1L, 1L, 1L, 1L, 1L, 1L, 1L, -1L, -1L, -1L, -1L, -1L, 1L, 
          1L, 1L, 1L, 1L, -1L, -1L, -1L, -1L, -1L, -1L, 1L, 1L, 1L, 1L, 
          1L, -1L, -1L, -1L, -1L, -1L, 1L))

#'@export
xs5.key <- list(
  subscales = c("N1", "N2", "N3", "N4", "N5", "N6", "E1", 
               "E2", "E3", "E4", "E5", "E6", "O1", "O2", "O3", "O4", "O5", "O6", 
               "A1", "A2", "A3", "A4", "A5", "A6", "C1", "C2", "C3", "C4", "C5", 
               "C6"), 
  domains = c("N", "E", "O", "A", "C"), 
  Mid = 0, 
  lims = c(-3, 3, -3, 3), 
  key = c("N1", "E1", "O1", "A1", "E6", "O6", "C6", 
          "E2", "O2", "C2", "A5x", "E5", "O5", "C5", "C3", "N4", "A4", 
          "A5x", "E4", "O4", "C4", "N3", "E3", "O3", "A3", "N5", "A5", 
          "A5x", "N2", "A2", "N6", "A6", "C1", "A5x"), 
  key2 = c("N", "E", 
         "O", "A", "E", "O", "C", "E", "O", "C", "A5x", "E", "O", "C", 
         "C", "N", "A", "A5x", "E", "O", "C", "N", "E", "O", "A", "N", 
          "A", "A5x", "N", "A", "N", "A", "C", "A5x"), 
  rev = c(1L, 1L, 
          1L, 1L, -1L, -1L, -1L, 1L, 1L, 1L, -1L, -1L, -1L, -1L, 1L, -1L, 
          -1L, 1L, 1L, 1L, 1L, -1L, -1L, -1L, -1L, 1L, 1L, -1L, -1L, -1L, 
          1L, 1L, -1L, 1L), 
  items = c("I am often nervous, fearful, and anxious, and worry that something might go wrong.", 
            "I like people; I am friendly and open talking to strangers.", 
            "I have a vivid imagination. I like to fantasize and let my thoughts run free.", 
            "I trust people and I believe that everyone is honest and has good intentions most of the time.", 
            "I am a serious rather than a cheerful person. I have rarely been overflowing with joy.", 
            "I have quite traditional values; I am considered to be somewhat close-minded when it comes to the values of other cultures and other groups of people.", 
            "I often rush into action without considering the consequences of my actions and decisions.", 
            "I enjoy meeting and associating with a lot of people. I take pleasure in the company of others - the more people, the better.", 
            "I have a deep appreciation for fine arts and beauty. I am much impressed by and interested in music, poetry, and art.", 
            "I am a methodical person and I love cleanliness and order. I want every thing to be in its right place.", 
            "I think highly of myself. I like to show others my knowledge and skills.", 
            "I am not looking for excitement or adventures. I do not like to take risks.", 
            "I am not interested in abstract or theoretical ideas. In my mind, ideas without practical applications are a waste of time.", 
            "I often postpone difficult or unpleasant activities and leave things unfinished. It is difficult for me to pull myself together and do the things that I have to.", 
            "I am a reliable person, who values ethical principles; I keep my promises and work carefully and thoroughly.", 
            "I feel comfortable around other people; Most of the time I am not bothered by teasing or by embarrassing situations.", 
            "I am a stubborn person who often gets into arguments; I openly express my anger or my dislike for someone.", 
            "Nobody would consider me arrogant. I do not brag about myself and my accomplishments.", 
            "I am active and I like to keep myself busy; I often feel bursting with energy.", 
            "I like to try different activities, to visit different places, to try out unfamiliar and exotic things from time to time; I love novelty and variety.", 
            "I know for certain what I want to accomplish and I work hard for it.", 
            "I rarely feel hopeless; I do not tend to blame myself needlessly. In general, I am content with myself and my life.", 
            "I prefer to remain unnoticed in the background. I often let other people talk and decide things on my behalf.", 
            "My feelings are not important to me; most of the time I do not pay any attention to them.", 
            "I do not want to deal with other people's problems; I am considered a selfish and egotistical person.", 
            "It is very difficult for me to resist temptation and to keep my desires and feelings in check; I do things that I regret later.", 
            "I do not want to be in the centre of attention. I do not like to talk about myself or my accomplishments.", 
            "I believe that I am, in several respects, better than others, and deserve more attention than others.", 
            "I am a well composed person and it is difficult to upset or anger me.", 
            "I believe that honesty does not take one very far in life; When necessary, I try to take advantage of others.", 
            "I often feel helpless and indecisive, especially in complicated situations. I easily lose my nerve when I feel that I cannot cope.", 
            "I believe that every person deserves respect. I feel compassion for those people who have been less lucky in life than I have.", 
            "I often feel that I am not competent enough to do something; I am not very productive and effective in my work.", 
            "I do not want to stand out with anything. I avoid talking about myself."
            ))
xs5.key2 <- xs5.key
xs5.key2$key <- c("N1", "E1", "O1", "A1", "E6", "O6", "C6", "E2", "O2", "C2", 
                  "A5x", "E5", "O5", "C5", "C3", "N4", "A4", "A5x", "E4", "O4", 
                  "C4", "N3", "E3", "O3", "A3", "N5", "A5old", "A5", "N2", "A2", 
                  "N6", "A6", "C1", "A5x")
xs5.key2$key2 <- c("N", "E", "O", "A", "E", "O", "C", "E", "O", "C", "A5x", "E", 
                   "O", "C", "C", "N", "A", "A5x", "E", "O", "C", "N", "E", "O", 
                   "A", "N", "A5old", "A", "N", "A", "N", "A", "C", "A5x")
#'@export
xs5.key2